USE DATABASE_PROJECT;

DROP TABLE IF EXISTS DATA_TABLE;
DROP TABLE IF EXISTS TIME_DIMENSION;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS KPI;

CREATE TABLE COUNTRY (
	COUNTRY_ISO3	CHAR(3) NOT NULL PRIMARY KEY,
    COUNTRY_ISO2	CHAR(2),
    NAME			VARCHAR(100),
    REGION			VARCHAR(100),
    ADMIN_REGION	VARCHAR(100),
    INCOME_LEVEL	VARCHAR(100),
    LENDING_TYPE	VARCHAR(100),
    CAPITAL_CITY	VARCHAR(100),
    LONGITUDE		FLOAT(10),
    LATITUDE		FLOAT(10),
    LANGUAGE		CHAR(2)
);

CREATE TABLE TIME_DIMENSION (
	ID				INTEGER PRIMARY KEY,
    DB_DATE			DATE NOT NULL,
    YEAR			INTEGER NOT NULL,
    MONTH			INTEGER NOT NULL,
    DAY				INTEGER NOT NULL,
    QUARTER			INTEGER NOT NULL,
    WEEK			INTEGER NOT NULL,
    DAY_NAME		VARCHAR(9) NOT NULL,
    MONTH_NAME		VARCHAR(9) NOT NULL,
    HOLIDAY_FLAG	CHAR(1) DEFAULT 'F' CHECK (HOLIDAY_FLAG IN ('T', 'F')),
    WEEKEND_FLAG	CHAR(1) DEFAULT 'F' CHECK (WEEKEND_FLAG IN ('T', 'F')),
    EVENT			VARCHAR(50),
    UNIQUE TD_YMD_IDX (YEAR, MONTH, DAY),
    UNIQUE TD_DBDATE_IDX (DB_DATE)
);

DROP PROCEDURE IF EXISTS FILL_DATE_DIMENSION;

DELIMITER //
CREATE PROCEDURE FILL_DATE_DIMENSION(IN STARTDATE DATE, IN STOPDATE DATE)
BEGIN
	DECLARE CURRENTDATE DATE;
    SET CURRENTDATE = STARTDATE;
    WHILE CURRENTDATE < STOPDATE DO
		INSERT INTO TIME_DIMENSION VALUES (
			YEAR(CURRENTDATE) * 10000 + MONTH(CURRENTDATE) * 100 + DAY(CURRENTDATE),
            CURRENTDATE,
            YEAR(CURRENTDATE),
            MONTH(CURRENTDATE),
            DAY(CURRENTDATE),
            QUARTER(CURRENTDATE),
            WEEKOFYEAR(CURRENTDATE),
            DATE_FORMAT(CURRENTDATE, '%W'),
            DATE_FORMAT(CURRENTDATE, '%M'),
            'F',
            CASE DAYOFWEEK(CURRENTDATE)
				WHEN 1 THEN 'T'
                WHEN 7 THEN 'T'
                ELSE 'F'
			END,
            NULL);
		SET CURRENTDATE = ADDDATE(CURRENTDATE, INTERVAL 1 DAY);
	END WHILE;
END//
DELIMITER ;

TRUNCATE TABLE TIME_DIMENSION;

CALL FILL_DATE_DIMENSION('1960-01-01', '1969-12-31');
CALL FILL_DATE_DIMENSION('1970-01-01', '1979-12-31');
CALL FILL_DATE_DIMENSION('1980-01-01', '1989-12-31');
CALL FILL_DATE_DIMENSION('1990-01-01', '1999-12-31');
CALL FILL_DATE_DIMENSION('2000-01-01', '2009-12-31');
CALL FILL_DATE_DIMENSION('2010-01-01', '2019-12-31');
CALL FILL_DATE_DIMENSION('2020-01-01', '2029-12-31');
CALL FILL_DATE_DIMENSION('2030-01-01', '2039-12-31');
CALL FILL_DATE_DIMENSION('2040-01-01', '2049-12-31');
CALL FILL_DATE_DIMENSION('2050-01-01', '2059-12-31');

CREATE TABLE KPI (
	INDICATOR		VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME			TEXT,
    SOURCE			TEXT,
    SOURCE_NOTES	TEXT,
    SUBJECT_NOTES 	TEXT,
    LANGUAGE 		CHAR(2),
    UNITS			VARCHAR(50),
    SCALE			VARCHAR(8)
);

CREATE TABLE DATA_TABLE (
	COUNTRY_ISO3	CHAR(3) NOT NULL,
    DATE			INTEGER NOT NULL,
    VALUE			FLOAT,
    INDICATOR		VARCHAR(50) NOT NULL,
    PRIMARY KEY (COUNTRY_ISO3, INDICATOR, DATE),
    FOREIGN KEY (COUNTRY_ISO3) REFERENCES COUNTRY(COUNTRY_ISO3),
    FOREIGN KEY (DATE) REFERENCES TIME_DIMENSION(YEAR),
    FOREIGN KEY (INDICATOR) REFERENCES KPI(INDICATOR));