USE REPOSITORIO_DATOS;
GO

IF OBJECT_ID('dbo.DATA_TABLE', 'U') IS NOT NULL
	DROP TABLE dbo.DATA_TABLE;
GO

IF OBJECT_ID('dbo.TIME_DIMENSION', 'U') IS NOT NULL
	DROP TABLE dbo.TIME_DIMENSION;
GO

IF OBJECT_ID('dbo.COUNTRY', 'U') IS NOT NULL
	DROP TABLE dbo.COUNTRY;
GO

IF OBJECT_ID('dbo.KPI', 'U') IS NOT NULL
	DROP TABLE dbo.KPI;
GO

CREATE TABLE COUNTRY (
	COUNTRY_ISO3	CHAR(3) NOT NULL PRIMARY KEY,
    COUNTRY_ISO2	CHAR(2),
    NAME			VARCHAR(100),
    REGION			VARCHAR(100),
    ADMIN_REGION	VARCHAR(100),
    INCOME_LEVEL	VARCHAR(100),
    LENDING_TYPE	VARCHAR(100),
    CAPITAL_CITY	VARCHAR(100),
    LONGITUDE		FLOAT(10),
    LATITUDE		FLOAT(10),
    LANGUAGE		CHAR(2)
);
GO

CREATE TABLE KPI (
	INDICATOR		VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME			TEXT,
    SOURCE			TEXT,
    SOURCE_NOTES	TEXT,
    SUBJECT_NOTES 	TEXT,
    LANGUAGE 		CHAR(2),
    UNITS			VARCHAR(50),
    SCALE			VARCHAR(8)
);
GO

CREATE TABLE TIME_DIMENSION (
	ID				INTEGER PRIMARY KEY,
    DB_DATE			DATE NOT NULL,
    YEAR			INTEGER NOT NULL,
    MONTH			INTEGER NOT NULL,
    DAY				INTEGER NOT NULL,
    QUARTER			INTEGER NOT NULL,
    WEEK			INTEGER NOT NULL,
    DAY_NAME		VARCHAR(9) NOT NULL,
    MONTH_NAME		VARCHAR(9) NOT NULL,
    HOLIDAY_FLAG	CHAR(1) DEFAULT 'F' CHECK (HOLIDAY_FLAG IN ('T', 'F')),
    WEEKEND_FLAG	CHAR(1) DEFAULT 'F' CHECK (WEEKEND_FLAG IN ('T', 'F')),
    EVENT			VARCHAR(50),
    CONSTRAINT TD_YMD_IDX UNIQUE (YEAR, MONTH, DAY),
    CONSTRAINT TD_DBDATE_IDX UNIQUE (DB_DATE)
);
GO
SELECT * FROM TIME_DIMENSION;
IF OBJECT_ID('FILL_DATE_DIMENSION', 'P') IS NOT NULL
	DROP PROCEDURE FILL_DATE_DIMENSION;
GO

CREATE PROCEDURE FILL_DATE_DIMENSION
	@STARTDATE DATE,
	@STOPDATE DATE
AS
BEGIN
	DECLARE @CURRENTDATE DATE;
    SET @CURRENTDATE = @STARTDATE;
    WHILE (@CURRENTDATE < @STOPDATE)
	BEGIN
		INSERT INTO dbo.TIME_DIMENSION VALUES (
			YEAR(@CURRENTDATE) * 10000 + MONTH(@CURRENTDATE) * 100 + DAY(@CURRENTDATE),
            @CURRENTDATE,
            YEAR(@CURRENTDATE),
            MONTH(@CURRENTDATE),
            DAY(@CURRENTDATE),
            DATEPART(QUARTER, @CURRENTDATE),
            DATEPART(WEEK, @CURRENTDATE),
            DATENAME(DAY, @CURRENTDATE),
            DATENAME(MONTH, @CURRENTDATE),
            'F',
            CASE DATEPART(WEEKDAY, @CURRENTDATE)
				WHEN 1 THEN 'T'
                WHEN 7 THEN 'T'
                ELSE 'F'
			END,
            NULL);
		SET @CURRENTDATE = DATEADD(DAY, 1, @CURRENTDATE);
	END;
END;
GO

TRUNCATE TABLE TIME_DIMENSION;
GO

EXEC FILL_DATE_DIMENSION @STARTDATE = '1960-01-01', @STOPDATE = '2059-12-31';
GO

CREATE TABLE DATA_TABLE (
	COUNTRY_ISO3	CHAR(3) NOT NULL FOREIGN KEY REFERENCES COUNTRY(COUNTRY_ISO3),
    DATE			INTEGER NOT NULL FOREIGN KEY REFERENCES TIME_DIMENSION(YEAR),
    VALUE			FLOAT,
    INDICATOR		VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES KPI(INDICATOR),
    PRIMARY KEY (COUNTRY_ISO3, INDICATOR, DATE));
GO