USE REPOSITORIO_DATOS;
GO

SELECT * FROM LANGUAGES;

SELECT * FROM DATA_TABLE;
SELECT * FROM COUNTRY;

SELECT * FROM KPI
WHERE SOURCE LIKE 'WEO_Apr_22';

SELECT *
FROM DATA_TABLE
WHERE INDICATOR = 'SI.POV.GINI';

SELECT DISTINCT INDICATOR
FROM DATA_TABLE;

SELECT *
FROM KPI
WHERE INDICATOR LIKE 'NY.GDP.MKTP.CD';

SELECT * FROM KPI
WHERE SOURCE LIKE 'WEO_Apr_22';

SELECT C.COUNTRY_ISO3, C.NAME, C.REGION, C.INCOME_LEVEL, K.INDICATOR, K.NAME, DT.DATE, DT.VALUE
FROM DATA_TABLE DT
JOIN COUNTRY C ON
	DT.COUNTRY_ISO3 = C.COUNTRY_ISO3
JOIN KPI  K ON
	DT.INDICATOR = K.INDICATOR
JOIN LANGUAGES L ON
	K.LANGUAGE = L.ID AND
	K.LANGUAGE = C.LANGUAGE
WHERE
	DT.VALUE IS NOT NULL AND
    C.NAME IS NOT NULL AND
    DT.DATE BETWEEN 2015 AND 2021 AND
    C.COUNTRY_ISO3 LIKE 'DOM' AND
	L.ID = 0 AND
	K.SOURCE LIKE 'WEO_Apr_22';