USE REPOSITORIO_DATOS;
GO

SELECT * FROM LANGUAGES;
SELECT * FROM DATA_TABLE;
SELECT * FROM COUNTRY;
SELECT * FROM KPI;
GO

/* How many KPIs are there (by source)? Note: this includes KPIs without data.*/
SELECT SOURCE, COUNT(*)
FROM KPI
GROUP BY SOURCE;
GO

/* How many KPIs are there (by source)? Note: this DOES NOT include KPIs without data.*/
SELECT K.SOURCE, COUNT(DISTINCT K.INDICATOR)
FROM DATA_TABLE AS DT
LEFT JOIN KPI AS K ON
	K.INDICATOR = DT.INDICATOR
GROUP BY K.SOURCE;
GO

/* Lists all KPIs by source. Note: this DOES NOT include KPIs without data.*/
SELECT 
	K.SOURCE,
	K.INDICATOR
FROM DATA_TABLE AS DT
LEFT JOIN KPI AS K ON
	DT.INDICATOR = K.INDICATOR AND
	DT.LANGUAGE = K.LANGUAGE
GROUP BY K.SOURCE, K.INDICATOR
ORDER BY K.SOURCE, K.INDICATOR;
GO

/* Testing whether a certain KPI is load in the DATA_TABLE table.*/
SELECT *
FROM DATA_TABLE
WHERE INDICATOR = 'SI.POV.GINI';
GO

/* Testing whether a certain KPI is load in the KPI table.*/
SELECT *
FROM KPI
WHERE INDICATOR LIKE 'NY.GDP.MKTP.CD';
GO

/* Viewing all KPIs in KPI table which source is IMF's WEO_Apr_22.*/
SELECT *
FROM KPI
WHERE SOURCE LIKE 'WEO_Apr_22';
GO

/* Viewing all KPIs in DATA_TABLE table.*/
SELECT DISTINCT INDICATOR
FROM DATA_TABLE;
GO

/* First template for the Excel template/sample view.*/
SELECT
	C.COUNTRY_ISO3,
	C.NAME,
	C.REGION,
	C.INCOME_LEVEL,
	K.INDICATOR,
	K.NAME,
	DT.DATE,
	DT.VALUE
FROM DATA_TABLE AS DT
JOIN COUNTRY AS C ON
	DT.COUNTRY_ISO3 = C.COUNTRY_ISO3
JOIN KPI AS K ON
	DT.INDICATOR = K.INDICATOR
JOIN LANGUAGES AS L ON
	K.LANGUAGE = L.ID AND
	K.LANGUAGE = C.LANGUAGE
WHERE
	DT.VALUE IS NOT NULL AND
    C.NAME IS NOT NULL AND
    DT.DATE BETWEEN 2015 AND 2021 AND
    C.COUNTRY_ISO3 LIKE 'DOM' AND
	L.ID = 0 AND
	K.SOURCE LIKE 'WEO_Apr_22';
GO

/* Final template for the Excel template/sample view.*/
SELECT
	C.COUNTRY_ISO3,
	C.COUNTRY_ISO2,
	C.NAME AS COUNTRY,
	C.REGION,
	C.INCOME_LEVEL,
	C.LENDING_TYPE,
	C.CAPITAL_CITY,
	K.INDICATOR AS INDICATOR_CODE,
	CASE										/* Reason: IMF names their KPIs the same when it only changes the units of measurement.*/
		WHEN K.UNITS IS NULL THEN K.NAME		/* Hence, KPIs code is unique, but it's not named uniquely. But the combination of name */
		ELSE CONCAT(K.NAME, ' (', K.UNITS, ')')	/* and units of measurement is indeed unique. */
	END AS INDICATOR,
	K.SOURCE,
	K.SOURCE_NOTES,
	K.SUBJECT_NOTES,
	L.LANGUAGE,
	DT.DATE AS YEAR,
	DT.VALUE
FROM DATA_TABLE AS DT
JOIN COUNTRY AS C ON
	DT.COUNTRY_ISO3 = C.COUNTRY_ISO3
JOIN KPI AS K ON
	DT.INDICATOR = K.INDICATOR
JOIN LANGUAGES AS L ON
	K.LANGUAGE = L.ID AND
	K.LANGUAGE = C.LANGUAGE
WHERE
	DT.VALUE IS NOT NULL AND
	C.NAME IS NOT NULL AND
	K.NAME IS NOT NULL;
GO